In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import BatchNormalization, LayerNormalization

# Generate random dataset
x = np.random.randint(1, 100, size=(5, 4)).astype(np.float32)

print("Original Input:")
print(x)

# Batch Normalization
batch_norm = BatchNormalization()
batch_output = batch_norm(x, training=True)

print("\nBatch Normalization Output:")
print(batch_output.numpy())

# Layer Normalization
layer_norm = LayerNormalization()
layer_output = layer_norm(x)

print("\nLayer Normalization Output:")
print(layer_output.numpy())

print("\nComparison:")
print("1. Batch Normalization normalizes data using batch statistics.")
print("2. Layer Normalization normalizes each sample independently.")
print("3. Batch Normalization depends on batch size, while Layer Normalization does not.")

enter a number: 23


the factorial of the given num is 25852016738884976640000
Original Input:
[[83. 70. 70. 87.]
 [46. 84. 83. 21.]
 [99. 73. 79. 63.]
 [68. 72. 43. 94.]
 [ 2. 58. 57. 66.]]

Batch Normalization Output:
[[ 0.69468296 -0.1689806   0.24458599  0.8147404 ]
 [-0.40374732  1.5208235   1.1278143  -1.770493  ]
 [ 1.1696798   0.19312096  0.8560519  -0.12534451]
 [ 0.24937332  0.07242012 -1.5898113   1.0889318 ]
 [-1.7099887  -1.6173835  -0.6386423  -0.00783372]]

Layer Normalization Output:
[[ 0.7206278  -0.98267365 -0.98267365  1.2447214 ]
 [-0.47136235  0.9615791   0.9238701  -1.4140868 ]
 [ 1.5597091  -0.41845846  0.03804159 -1.1792917 ]
 [-0.06905246  0.15191555 -1.4501023   1.3672397 ]
 [-1.7157674   0.48041475  0.44119728  0.79415524]]

Comparison:
1. Batch Normalization normalizes data using batch statistics.
2. Layer Normalization normalizes each sample independently.
3. Batch Normalization depends on batch size, while Layer Normalization does not.
